VetClinicManager/Models/Medication.cs
using System.ComponentModel.DataAnnotations;
namespace VetClinicManager.Models;

public class Medication
{
    [Key]
    public int Id { get; set; }
    
    [Required]
    [MaxLength(150)]
    public string Name { get; set; }

    public ICollection<AnimalMedication> AnimalMedications { get; set; } = new List<AnimalMedication>();
}

VetClinicManager/Areas/Admin/Controllers/MedicationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VetClinicManager.Areas.Admin.DTOs.Medications;
using VetClinicManager.Models;
using VetClinicManager.Services;

namespace VetClinicManager.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MedicationsController : Controller
    {
        private readonly IMedicationService _medicationService;

        public MedicationsController(IMedicationService medicationService)
        {
            _medicationService = medicationService;
        }

        // GET: Admin/Medications
        [Authorize(Roles = "Admin, Receptionist, Vet")]
        public async Task<IActionResult> Index()
        {
            var medicationListDtos = await _medicationService.GetAllMedicationsAsync();
            return View(medicationListDtos);
        }

        // GET: Admin/Medications/Details/5
        [Authorize(Roles = "Admin,Receptionist,Vet")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicationDto = await _medicationService.GetMedicationForDetailsAsync(id.Value);

            if (medicationDto == null)
            {
                return NotFound();
            }

            return View("Details", medicationDto);
        }

        // GET: Admin/Medications/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View(new MedicationCreateDto());
        }

        // POST: Admin/Medications/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(MedicationCreateDto createDto)
        {
            if (!ModelState.IsValid)
            {
                return View(createDto);
            }

            var resultDto = await _medicationService.CreateMedicationAsync(createDto);

            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/Medications/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editDto = await _medicationService.GetMedicationForEditAsync(id.Value);

            if (editDto == null)
            {
                return NotFound();
            }

            return View(editDto);
        }

        // POST: Admin/Medications/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, MedicationEditDto editDto)
        {
            if (id != editDto.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(editDto);
            }

            try
            {
                await _medicationService.UpdateMedicationAsync(editDto);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await _medicationService.MedicationExistsAsync(editDto.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            catch
            {
                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/Medications/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deleteDto = await _medicationService.GetMedicationForDeleteAsync(id.Value);

            if (deleteDto == null)
            {
                return NotFound();
            }

            return View(deleteDto);
        }

        // POST: Admin/Medications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _medicationService.DeleteMedicationAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

VetClinicManager/Areas/Admin/Views/Medications/Create.cshtml
@model VetClinicManager.Areas.Admin.DTOs.Medications.MedicationCreateDto

@{
    ViewData["Title"] = "Dodaj nowy lek/materiał";
    Layout = "_Layout";
}

<div class="container mt-4">
    <h1>@ViewData["Title"]</h1>

    <hr />

    <div class="row">
        <div class="col-md-6">
            <form asp-area="Admin" asp-controller="Medications" asp-action="Create" method="post">
                @if (!ViewData.ModelState.IsValid && ViewData.ModelState.ErrorCount > 0)
                {
                    <div asp-validation-summary="All" class="alert alert-danger"></div>
                }

                <div class="form-group mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group mt-4 d-flex">
                    <button type="submit" class="btn btn-primary">Dodaj
                    </button>
                    <a asp-area="Admin" asp-controller="Medications" asp-action="Index" class="btn btn-outline-secondary ms-2">
                        Anuluj
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VetClinicManager/Areas/Admin/Views/Medications/Delete.cshtml
@model VetClinicManager.Areas.Admin.DTOs.Medications.MedicationDeleteDto

@{
    ViewData["Title"] = "Usuń lek/materiał";
    Layout = "_Layout";
}

<div class="container mt-4">
    <h1>@ViewData["Title"]: @Model.Name</h1>
    <hr />

    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Potwierdzenie</h4>
        <p>Czy na pewno chcesz trwale usunąć ten lek/materiał z systemu? <strong>Tej operacji nie można cofnąć.</strong></p>
    </div>

    <div class="card mt-4">
        <div class="card-header">
            Szczegóły leku/materiału do usunięcia
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3 col-md-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9 col-md-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
        </div>
    </div>

    <form asp-area="Admin" asp-controller="Medications" asp-action="Delete" method="post" class="mt-4">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">Tak, usuń</button>
        <a asp-area="Admin" asp-controller="Medications" asp-action="Index" class="btn btn-outline-secondary ms-2">
            Anuluj
        </a>
    </form>
</div>

VetClinicManager/Areas/Admin/Views/Medications/Details.cshtml
@model VetClinicManager.Areas.Admin.DTOs.Medications.MedicationDeleteDto

@{
    ViewData["Title"] = "Szczegóły leku/materiału";
    Layout = "_Layout";
}

<div class="container mt-4">
    <h1>@ViewData["Title"]: @Model.Name</h1>
    <hr />

    <div class="card">
        <div class="card-header">
            Informacje
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3 col-md-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9 col-md-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
        </div>
    </div>

    <div class="mt-4">
        <a asp-area="Admin" asp-controller="Medications" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edytuj</a>
        <a asp-area="Admin" asp-controller="Medications" asp-action="Index" class="btn btn-outline-secondary ms-2">Powrót do listy</a>
    </div>

</div>

VetClinicManager/Areas/Admin/Views/Medications/Edit.cshtml
@model VetClinicManager.Areas.Admin.DTOs.Medications.MedicationEditDto

@{
    ViewData["Title"] = "Edytuj lek/materiał";
    Layout = "_Layout";
}

<div class="container mt-4">
    <h1>@ViewData["Title"]: @Model.Name</h1>

    <hr />
    <div class="row">
        <div class="col-md-6">
            <form asp-area="Admin" asp-controller="Medications" asp-action="Edit" method="post">
                @if (!ViewData.ModelState.IsValid && ViewData.ModelState.ErrorCount > 0)
                {
                    <div asp-validation-summary="All" class="alert alert-danger"></div>
                }
                
                <input type="hidden" asp-for="Id" />

                <div class="form-group mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group mt-4 d-flex">
                    <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
                    <a asp-area="Admin" asp-controller="Medications" asp-action="Index" class="btn btn-outline-secondary ms-2">
                        Anuluj
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VetClinicManager/Areas/Admin/Views/Medications/Index.cshtml
@model IEnumerable<VetClinicManager.Areas.Admin.DTOs.Medications.MedicationListDto>

@{
    ViewData["Title"] = "Zarządzanie lekami/materiałami";
    Layout = "_Layout";
}

<div class="container mt-4">
    <h1>@ViewData["Title"]</h1>

    <p class="mt-3">
        <a asp-area="Admin" asp-controller="Medications" asp-action="Create" class="btn btn-success">Dodaj nowy lek/materiał</a>
    </p>

    @if (Model == null || !Model.Any())
    {
        <div class="alert alert-info mt-3" role="alert">
            Brak leków/materiałów w systemie.
        </div>
    }
    else
    {
        <div class="table-responsive">
            <table class="table table-striped table-hover align-middle">
                <thead class="table-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <strong>@Html.DisplayFor(modelItem => item.Name)</strong>
                            </td>
                            <td>
                                <a asp-area="Admin" asp-controller="Medications" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary" title="Edytuj lek/materiał">Edytuj</a>
                                <a asp-area="Admin" asp-controller="Medications" asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-info ms-1" title="Szczegóły leku/materiału">Szczegóły</a>
                                <a asp-area="Admin" asp-controller="Medications" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger ms-1" title="Usuń lek/materiał">Usuń</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }

</div>